from pathlib import Path
from typing import Iterable

def read_tasks(file: Path): ...
def add_tasks(additions: Iterable[str], file: Path): ...
def delete_tasks(deletions: Iterable[str], file: Path): ...
def update_tasks(updates: Iterable[str], file: Path): ...
