import datetime as dt
from typing import Any, Dict, List, Optional

class Task:
    description: str
    done: bool = ...
    priority: Optional[str] = ...
    completed_at: Optional[dt.date] = ...
    created_at: dt.date = ...
    projects: List[str] = ...
    contexts: List[str] = ...
    tags: Dict = ...
    @classmethod
    def from_todotxt(cls, todotxt: Any): ...
    def __init__(self) -> None: ...
    def __ne__(self, other: Any) -> Any: ...
    def __eq__(self, other: Any) -> Any: ...
    def __lt__(self, other: Any) -> Any: ...
    def __le__(self, other: Any) -> Any: ...
    def __gt__(self, other: Any) -> Any: ...
    def __ge__(self, other: Any) -> Any: ...

class Event:
    event_type: str
    tasks: List[str]
    file: str
    prior_hash: str
    new_hash: str
    occurred_at: dt.datetime = ...
    def to_dict(self): ...
    def __init__(self) -> None: ...
    def __ne__(self, other: Any) -> Any: ...
    def __eq__(self, other: Any) -> Any: ...
    def __lt__(self, other: Any) -> Any: ...
    def __le__(self, other: Any) -> Any: ...
    def __gt__(self, other: Any) -> Any: ...
    def __ge__(self, other: Any) -> Any: ...
